node test-of-basic-tree-01.js
node test-of-query-api.js
node test-of-dataset-sync-methods.js
node test-of-basic-auth-01.js
node test-of-select-by-uid-and-others.js
node test-of-controller-language.js
node test-of-default.js
node test-of-server.js
node test-of-dataset-proxy.js
node test-of-complex-query.js
node test-of-relations-schema.js
node test-of-uniqueness.js
node test-of-modify-all.js
node test-of-rescheming.js
node test-of-renaming.js
node test-of-trigger.js
node test-of-persistence.js
node test-on-readme.js
node test.js
# node test-of-performance.js